# OrangeFox settings for UMS512_1H10
OF_HIDE_NOTCH := 0  
OF_USE_GREEN_LED := 0  
OF_FLASHLIGHT_ENABLE := 1  
OF_ALLOW_DISABLE_NAVBAR := 0  
OF_SPLASH_MAX_SIZE := "65"  
OF_ADVANCED_SECURITY := 0  
OF_SCREEN_H := 1600  # From device specs[1][34]  
OF_STATUS_H := 80  
OF_CLOCK_POS := 1  
